# Generated by Django 5.1.4 on 2025-01-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Toyota', 'Toyota')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('horsepower', models.PositiveIntegerField()),
                ('engine_displacement', models.CharField(choices=[('1.0', '1.0L'), ('1.2', '1.2L'), ('1.4', '1.4L'), ('1.6', '1.6L'), ('1.8', '1.8L'), ('2.0', '2.0L'), ('2.5', '2.5L'), ('3.0', '3.0L'), ('3.5', '3.5L'), ('4.0', '4.0L'), ('5.0', '5.0L'), ('6.0', '6.0L')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
