# Generated by Django 5.1.4 on 2025-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_car_currency_alter_car_price_alter_car_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
