# Generated by Django 5.1.4 on 2025-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.CharField(choices=[('1.0 L', '1.0 L'), ('1.2 L', '1.2 L'), ('1.4 L', '1.4 L'), ('1.6 L', '1.6 L'), ('1.8 L', '1.8 L'), ('2.0 L', '2.0 L'), ('2.5 L', '2.5 L'), ('3.0 L', '3.0 L'), ('3.5 L', '3.5 L'), ('4.0 L', '4.0 L'), ('5.0 L', '5.0 L'), ('6.0 L', '6.0 L')], max_length=7),
        ),
    ]
